# Workflow for running Python tests across multiple platforms
name: Simple Python Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        # Test on three different operating systems
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    # Install required packages
    - name: Install dependencies
      run: |
        # pip install python-copasi==4.45.296  # Install specific version of COPASI
        pip install -r requirements.txt
    
    # Execute the test script
    - name: Run Python script
      run: |
        python test_load_model.py
